[tools]
zellij = "latest"
"aqua:nushell/nushell" = "latest"
pi = "latest"
rust = "stable"
rust-analyzer = "latest"
"cargo:dotter" = { version = "latest", depends = ["rust"] }
"github:nextest-rs/nextest" = { version = "latest", version_prefix = "cargo-nextest-" }
